---
abstract: 'parse and split russian geographical names'
author:
  - 'liosha <liosha@cpan.org>'
build_requires:
  Encode: 0
  Encode::Locale: 0
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Names-Russian
requires:
  Exporter: 0
  List::MoreUtils: 0
  perl: 5.010
  utf8: 0
version: 0.01_1
